[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Set the serial monitor speed to match your setup() code
monitor_speed = 115200 

; List the external libraries your project needs
lib_deps = 
	tzapu/WiFiManager @ ^2.0.16-rc.2
	adafruit/RTClib @ ^2.1.4









































































	